name: Go CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19, 1.20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Run tests
      run: |
        go test ./tests -v

    - name: Check branch for test requirement
      if: github.ref == 'refs/heads/main'
      run: |
        if [ $? -ne 0 ]; then
          echo "Tests failed on main, failing the build.";
          exit 1;
        fi

    - name: Notify success
      if: github.ref != 'refs/heads/main'
      run: echo "Tests ran successfully or were skipped, no failure required on dev branch."
